using System.Collections.Generic;

namespace Keycloak.ASPNet.Angular.Api.Models;

/// <summary>
/// A keycloak jwt client roles.
/// </summary>
/// <autogeneratedoc />
public class KeycloakJwtClientRoles : Dictionary<string, KeycloakJwtRoleContainer>
{
}