using Microsoft.AspNetCore.Authentication;
using System.Diagnostics.CodeAnalysis;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Keycloak.ASPNet.Angular.Api.Filters;

/// <summary>
/// Transforms provider specific roles to default role claims.
/// </summary>
/// <example>
/// {
///   "realm_access": {
///     "roles": [
///       "offline_access",
///       "uma_authorization"
///     ]
///   },
///   "resource_access": {
///     "api": {
///       "roles": [
///         "manage"
///       ]
///     },
///   },
/// }
/// </example>
/// <seealso cref="IClaimsTransformation" />
[SuppressMessage("ReSharper", "ClassNeverInstantiated.Global", Justification = "Instantiated via DI.")]
public class JwtRoleTransformation : IClaimsTransformation
{
    private readonly JwtRoleTransformationTenant _tenantRoleTransformation;
    private readonly JwtRoleTransformationAudience _audienceRoleTransformation;

    /// <summary>
    /// Initializes a new instance of the <see cref="JwtRoleTransformation"/> class.
    /// </summary>
    /// <param name="tenantRoleTransformation">The tenant role transformation.</param>
    /// <param name="audienceRoleTransformation">The audience role transformation.</param>
    /// <autogeneratedoc />
    public JwtRoleTransformation(JwtRoleTransformationTenant tenantRoleTransformation, JwtRoleTransformationAudience audienceRoleTransformation)
    {
        _tenantRoleTransformation = tenantRoleTransformation;
        _audienceRoleTransformation = audienceRoleTransformation;
    }

    /// <summary>
    /// Provides a central transformation point to change the specified principal.
    /// Note: this will be run on each AuthenticateAsync call, so its safer to
    /// return a new ClaimsPrincipal if your transformation is not idempotent.
    /// </summary>
    /// <param name="principal">The <see cref="T:System.Security.Claims.ClaimsPrincipal" /> to transform.</param>
    /// <returns>
    /// The transformed principal.
    /// </returns>
    public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
        var result = principal.Clone();
        result = await _tenantRoleTransformation.TransformAsync(result);
        result = await _audienceRoleTransformation.TransformAsync(result);
        return result;
    }
}